# Site settings
title: Under construction
author: Michael Holmboe
  name: Michael Holmboe
  email: michael.holmboe@umu.se
description: "Great site about MINFF."

# Build settings
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
